# This workflow will upload a Python package in the official FIREWHEEL ecosystem

name: Upload FIREHWEEL Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  call-firewheel-python-publish:
    uses: sandialabs/firewheel/.github/workflows/python-publish.yml@main
